### ISSUE TITLE
lettuce tutorial does not work?

### ISSUE THREAD

**Issue by jjgalvez** [iljabauer/lettuce3#1]
trying lettuce out for the first time and considering adding it to a pyramid project I have in python3. Going trough the tutorial from the lettuce site and I get the following error:

(lettuce) jc@Puker:~/dev/lettuce/pymath/tests$ lettuce 
/home/jc/dev/lettuce/lib/python3.4/site-packages/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher
  warnings.warn('Using slow pure-python SequenceMatcher')
========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
Traceback (most recent call last):
Died with unorderable types: int() < TypeError()
Traceback (most recent call last):
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/registry.py", line 136, in call_hook
    callback(*args, **kw)
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/plugins/colored_shell_output.py", line 190, in print_feature_running
    write_out("\n")
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/plugins/colored_shell_output.py", line 58, in write_out
    wrt(wp(what))
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/plugins/colored_shell_output.py", line 33, in wrt
    sys.stdout.write(what)
TypeError: must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/__init__.py", line 180, in run
    failfast=self.failfast))
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/core.py", line 1220, in run
    call_hook('before_each', 'feature', self)
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/registry.py", line 139, in call_hook
    traceback.print_exc(e)
  File "/usr/lib/python3.4/traceback.py", line 252, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "/usr/lib/python3.4/traceback.py", line 153, in _format_exception_iter
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))
  File "/usr/lib/python3.4/traceback.py", line 18, in _format_list_iter
    for filename, lineno, name, line in extracted_list:
  File "/usr/lib/python3.4/traceback.py", line 58, in _extract_tb_or_stack_iter
    while curr is not None and (limit is None or n < limit):
TypeError: unorderable types: int() < TypeError()
========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/registry.py", line 136, in call_hook
    callback(*args, **kw)
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/plugins/colored_shell_output.py", line 200, in print_end
    write_out("\n")
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/plugins/colored_shell_output.py", line 58, in write_out
    wrt(wp(what))
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/plugins/colored_shell_output.py", line 33, in wrt
    sys.stdout.write(what)
TypeError: must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jc/dev/lettuce/bin/lettuce", line 9, in <module>
    load_entry_point('lettuce==0.2.20', 'console_scripts', 'lettuce')()
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/bin.py", line 120, in main
    result = runner.run()
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/__init__.py", line 200, in run
    call_hook('after', 'all', total)
  File "/home/jc/dev/lettuce/lib/python3.4/site-packages/lettuce/registry.py", line 139, in call_hook
    traceback.print_exc(e)
  File "/usr/lib/python3.4/traceback.py", line 252, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "/usr/lib/python3.4/traceback.py", line 153, in _format_exception_iter
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))
  File "/usr/lib/python3.4/traceback.py", line 18, in _format_list_iter
    for filename, lineno, name, line in extracted_list:
  File "/usr/lib/python3.4/traceback.py", line 58, in _extract_tb_or_stack_iter
    while curr is not None and (limit is None or n < limit):
TypeError: unorderable types: int() < TypeError()
(lettuce) jc@Puker:~/dev/lettuce/pymath/tests$

**Comment by iljabauer** [comment]
Hi, this is not the official repository of lettuce. Please take a look at https://github.com/gabrielfalcao/lettuce

Also lettuce is not working good with python3 so I switched to behave (https://github.com/behave/behave)

**Comment by jjgalvez** [comment]
Thanks I've recently been looking at behave as well and it seems to work 
better with python3
